version: '2'
services:
  app:
    build: .
    volumes:
      - ./:/app
    ports:
      - 8080:5173
    command: ["npm", "run", "dev", "--", "--host", "0.0.0.0", "--port", "5173"]
    environment:
      - CHOKIDAR_USEPOLLING=true